### ISSUE TITLE
Idea for another doki-theme repository

### ISSUE THREAD

**Issue by nopeless** [doki-theme/doki-build-source#3]
First of all, sorry if this is not the appropriate place to ask this question. If this is the case, please let me know the correct place (or ask me to email)

I have read the build source and I would like to port this to [MusicBee themes](https://www.getmusicbee.com/addons/s/?type=1). Is there a documentation for this?

**Comment by Unthrottled** [comment]
No worries, I'll eventually getting around to setting up the github discussion on the master theme repo. That's where I'd like to have future discussions about that. I'll let you know when I've done it, but you can use this issue for now.

There isn't dedicated documentation, but you can check out the contributing files on various projects on how it works. Here's a few:

- https://github.com/doki-theme/doki-theme-hyper/blob/master/CONTRIBUTING.md#outline
- https://github.com/doki-theme/doki-theme-vscode/blob/master/CONTRIBUTING.md#outline
- https://github.com/doki-theme/doki-theme-github/blob/master/CONTRIBUTING.md#outline

You can use the template to give you a jump start https://github.com/doki-theme/doki-theme-template

Anyways, once you feel like you've gotten it to a place where you are happy with it. We can have further discussions about what would be needed for me to adopt it. Thanks!

**Comment by nopeless** [comment]
Thanks!

**Comment by nopeless** [comment]
@Unthrottled 

https://github.com/nopeless/doki-theme-musicbee

Here

**Comment by Unthrottled** [comment]
Cool! Thanks, I might have some time to review maybe next weekend or so. I have some things I'd like to finish up first.

**Comment by nopeless** [comment]
> Cool! Thanks, I might have some time to review maybe next weekend or so. I have some things I'd like to finish up first.

Take your time
